"""Thin re-export layer for command handlers after refactor."""

from handlers.commands_admin import ADMIN_COMMANDS_TEXT, admin_help_command
from handlers.commands_consilium import consilium_command, execute_consilium_request
from handlers.commands_core import (
    admin_command,
    clear_memory_command,
    header_off_command,
    header_on_command,
    help_command,
    new_dialog,
    start,
)
from handlers.commands_flows import (
    flow_command,
    setflow_command,
    show_discord_chats_command,
    show_tg_chats_command,
    unsetflow_command,
)
from handlers.commands_models import (
    MODELS_HINT_TEXT,
    _refresh_image_models,
    models_all_command,
    models_command,
    models_free_callback,
    models_free_command,
    models_large_context_command,
    models_paid_command,
    models_pic_command,
    models_specialized_command,
    models_voice_command,
    models_voice_log_command,
    set_pic_model_command,
    set_text_model_command,
)
from handlers.commands_routing import (
    routing_llm_command,
    routing_mode_command,
    routing_rules_command,
)
from handlers.commands_selftest import selftest_command
from handlers.commands_voice import (
    say_command,
    set_tts_voice_command,
    set_voice_log_model_command,
    set_voice_model_command,
    tts_voices_command,
    voice_log_debug_off_command,
    voice_log_debug_on_command,
    voice_msg_conversation_off_command,
    voice_msg_conversation_on_command,
    voice_send_raw_command,
    voice_send_segmented_command,
)
from services.generation import build_models_messages, fetch_models_data

__all__ = [
    "ADMIN_COMMANDS_TEXT",
    "MODELS_HINT_TEXT",
    "admin_command",
    "admin_help_command",
    "build_models_messages",
    "clear_memory_command",
    "consilium_command",
    "execute_consilium_request",
    "fetch_models_data",
    "flow_command",
    "header_off_command",
    "header_on_command",
    "help_command",
    "models_all_command",
    "models_command",
    "models_free_callback",
    "models_free_command",
    "models_large_context_command",
    "models_paid_command",
    "models_pic_command",
    "models_specialized_command",
    "models_voice_command",
    "models_voice_log_command",
    "new_dialog",
    "routing_llm_command",
    "routing_mode_command",
    "routing_rules_command",
    "say_command",
    "set_pic_model_command",
    "set_text_model_command",
    "set_tts_voice_command",
    "set_voice_log_model_command",
    "set_voice_model_command",
    "setflow_command",
    "selftest_command",
    "show_discord_chats_command",
    "show_tg_chats_command",
    "start",
    "tts_voices_command",
    "unsetflow_command",
    "voice_log_debug_off_command",
    "voice_log_debug_on_command",
    "voice_msg_conversation_off_command",
    "voice_msg_conversation_on_command",
    "voice_send_raw_command",
    "voice_send_segmented_command",
    "_refresh_image_models",
]
